In [2]:
from functions import DataBaseV2
import pandas as pd
import sys
import os
import sqlite3
import inspect
path = os.getcwd()
path_up = os.path.dirname(path)
sys.path.insert(0, path_up)

from stratégie_nettoyage_donnees import nettoyage_df

print(path_up)

/home/geoffroy/Projet-chef-d-oeuvre/E1/code

In [9]:
con = sqlite3.connect("db.db")

data_path = os.path.join(path_up, "data/survey.csv")
df = pd.read_csv(data_path)
df = nettoyage_df(df)
df['ids'] = df.index
df.to_sql('Questionnaires', con=con, if_exists='replace', index=False, dtype={'ids': 'INTEGER PRIMARY KEY AUTOINCREMENT'})

print("Les données ont été ajoutées en base.")

/home/geoffroy/Projet-chef-d-oeuvre/E1/code/stratégie_nettoyage_donnees.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["self_employed"].fillna("Other", inplace=True)
/home/geoffroy/Projet-chef-d-oeuvre/E1/code/stratégie_nettoyage_donnees.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["work_interfere"].fillna("Not concerned", inplace=True)

,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,ids
0,37,Female,Other,No,Yes,Often,6-25,No,Yes,Yes,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,0
1,44,Male,Other,No,No,Rarely,More than 1000,No,No,Don't know,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,1
2,32,Male,Other,No,No,Rarely,6-25,No,Yes,No,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,2
3,31,Male,Other,Yes,Yes,Often,26-100,No,Yes,No,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,3
4,31,Male,Other,No,No,Never,100-500,Yes,Yes,Yes,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,26,Male,No,No,Yes,Not concerned,26-100,No,Yes,No,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,1254
1255,32,Male,No,Yes,Yes,Often,26-100,Yes,Yes,Yes,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,1255
1256,34,Male,No,Yes,Yes,Sometimes,More than 1000,No,Yes,Yes,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,1256
1257,46,Female,No,No,No,Not concerned,100-500,Yes,Yes,No,...,Don't know,Yes,No,No,No,No,No,No,No,1257
1258,25,Male,No,Yes,Yes,Sometimes,26-100,No,No,Yes,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,1258

Les données ont été ajoutées en base.